export enum MaterialType {
  RUBBER = 'rubber',
  FOAM = 'foam',
  WOOL = 'wool',
  NUBUCK = 'nubuck',
  SUEDE = 'suede',
  FULL_GRAIN_LEATHER = 'full-grain leather',
  TOP_GRAIN_LEATHER = 'top-grain leather',
  SPLIT_GRAIN_LEATHER = 'split-grain Leather',
  GENUINE_LEATHER = 'genuine leather',
  EXOTIC_LEATHER = 'exotic leather',
  VEGETABLE_TANNED_LEATHER = 'vegetable-tanned leather',
  CHROME_TANNED_LEATHER = 'chrome-tanned leather',
  DISTRESSED_LEATHER = 'distressed leather',
  PULL_UP_LEATHER = 'pull-up leather',
}
